// Define the CardSymbol class
class CardSymbol {
  final String emoji;
  final String fileName;
  final String referralUrl;

  const CardSymbol(
      {required this.emoji, required this.fileName, required this.referralUrl});
}

const EXT = '.png';

// Declare the constant list of CardSymbol objects
const List<CardSymbol> SYMBOLS = [
  CardSymbol(emoji: '🚼', fileName: 'abort-146096$EXT', referralUrl: ''),
  CardSymbol(emoji: '🎨', fileName: 'abstract-1293487$EXT', referralUrl: ''),
  CardSymbol(emoji: '⚓', fileName: 'anchor-309481$EXT', referralUrl: ''),
  CardSymbol(emoji: '🍌', fileName: 'banana-5442390$EXT', referralUrl: ''),
  CardSymbol(emoji: '⚾', fileName: 'baseball-157928$EXT', referralUrl: ''),
  CardSymbol(emoji: '🏀', fileName: 'basketball-147794$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔋', fileName: 'battery-98396$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔔', fileName: 'bell-6478079$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐦', fileName: 'bird-6052752$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔵', fileName: 'blue-2024619$EXT', referralUrl: ''),
  CardSymbol(emoji: '📚', fileName: 'book-1296045$EXT', referralUrl: ''),
  CardSymbol(emoji: '🎳', fileName: 'bowling-157933$EXT', referralUrl: ''),
  CardSymbol(emoji: '💼', fileName: 'briefcase-308819$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐛', fileName: 'bug-1294574$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐂', fileName: 'bull-47524$EXT', referralUrl: ''),
  CardSymbol(emoji: '🦋', fileName: 'butterfly-5632904$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔘', fileName: 'button-305751$EXT', referralUrl: ''),
  CardSymbol(emoji: '🧮', fileName: 'calculator-23414$EXT', referralUrl: ''),
  CardSymbol(emoji: '📅', fileName: 'calendar-97868$EXT', referralUrl: ''),
  CardSymbol(emoji: '📷', fileName: 'camera-98398$EXT', referralUrl: ''),
  CardSymbol(emoji: '🃏', fileName: 'cards-98382$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐱', fileName: 'cat-3242632$EXT', referralUrl: ''),
  CardSymbol(emoji: '💿', fileName: 'cd-98417$EXT', referralUrl: ''),
  CardSymbol(emoji: '📈', fileName: 'chart-1296049$EXT', referralUrl: ''),
  CardSymbol(emoji: '🧀', fileName: 'cheese-3092936$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🧾',
      fileName: 'cheque-guarantee-card-2103509$EXT',
      referralUrl: ''),
  CardSymbol(emoji: '🍒', fileName: 'cherries-158241$EXT', referralUrl: ''),
  CardSymbol(emoji: '🎄', fileName: 'christmas-6830681$EXT', referralUrl: ''),
  CardSymbol(emoji: '⭕', fileName: 'circle-33085$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🎬', fileName: 'clapperboard-1078813$EXT', referralUrl: ''),
  CardSymbol(emoji: '🥥', fileName: 'coconut-1293036$EXT', referralUrl: ''),
  CardSymbol(emoji: '☕', fileName: 'coffee-6221625$EXT', referralUrl: ''),
  CardSymbol(emoji: '🌈', fileName: 'colorful-1197336$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🖱️', fileName: 'computer-mouse-152249$EXT', referralUrl: ''),
  CardSymbol(emoji: '🦀', fileName: 'crab-42880$EXT', referralUrl: ''),
  CardSymbol(emoji: '💎', fileName: 'diamond-6922292$EXT', referralUrl: ''),
  CardSymbol(emoji: '🚦', fileName: 'traffic-light-24177$EXT', referralUrl: ''),
  CardSymbol(emoji: '🎲', fileName: 'die-308887$EXT', referralUrl: ''),
  CardSymbol(emoji: '📜', fileName: 'diploma-152024$EXT', referralUrl: ''),
  CardSymbol(emoji: '👩‍⚕️', fileName: 'doctor-1295581$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐬', fileName: 'dolphin-41436$EXT', referralUrl: ''),
  CardSymbol(emoji: '🕊️', fileName: 'dove-41260$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐉', fileName: 'dragon-1526802$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐣', fileName: 'easter-6051942$EXT', referralUrl: ''),
  CardSymbol(emoji: '👀', fileName: 'eyes-155625$EXT', referralUrl: ''),
  CardSymbol(emoji: '👆', fileName: 'fingerprint-150159$EXT', referralUrl: ''),
  CardSymbol(emoji: '🌲', fileName: 'fir-tree-1096466$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔥', fileName: 'fire-6886617$EXT', referralUrl: ''),
  CardSymbol(emoji: '⚜️', fileName: 'fleur-de-lis-47621$EXT', referralUrl: ''),
  CardSymbol(emoji: '💾', fileName: 'floppy-disk-98413$EXT', referralUrl: ''),
  CardSymbol(emoji: '🌸', fileName: 'flower-156608$EXT', referralUrl: ''),
  CardSymbol(emoji: '🌼', fileName: 'flower-1969921$EXT', referralUrl: ''),
  CardSymbol(emoji: '📁', fileName: 'folder-97593$EXT', referralUrl: ''),
  CardSymbol(emoji: '🍽️', fileName: 'food-2028376$EXT', referralUrl: ''),
  CardSymbol(emoji: '🏈', fileName: 'football-157930$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐸', fileName: 'frog-157934$EXT', referralUrl: ''),
  CardSymbol(emoji: '🎃', fileName: 'halloween-23439$EXT', referralUrl: ''),
  CardSymbol(emoji: '🍔', fileName: 'hamburger-31775$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🧴', fileName: 'hand-sanitizer-5302594$EXT', referralUrl: ''),
  CardSymbol(emoji: '🤲', fileName: 'hands-6030186$EXT', referralUrl: ''),
  CardSymbol(emoji: '🎩', fileName: 'hat-157581$EXT', referralUrl: ''),
  CardSymbol(emoji: '🏠', fileName: 'home-25113$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐝', fileName: 'honeybee-42907$EXT', referralUrl: ''),
  CardSymbol(emoji: '⏳', fileName: 'hourglass-34237$EXT', referralUrl: ''),
  CardSymbol(emoji: '🏡', fileName: 'house-304005$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🎨', fileName: 'illustration-3092854$EXT', referralUrl: ''),
  CardSymbol(emoji: '🕹️', fileName: 'joystick-98408$EXT', referralUrl: ''),
  CardSymbol(emoji: '🥤', fileName: 'juice-42560$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔑', fileName: 'key-25114$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐞', fileName: 'ladybug-31674$EXT', referralUrl: ''),
  CardSymbol(emoji: '📺', fileName: 'lcd-32872$EXT', referralUrl: ''),
  CardSymbol(emoji: '🍋', fileName: 'lime-25314$EXT', referralUrl: ''),
  CardSymbol(emoji: '📍', fileName: 'location-light$EXT', referralUrl: ''),
  CardSymbol(emoji: '🦦', fileName: 'mammal-5711107$EXT', referralUrl: ''),
  CardSymbol(emoji: '🍁', fileName: 'maple-leaf-38777$EXT', referralUrl: ''),
  CardSymbol(emoji: '💰', fileName: 'money-576443$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐒', fileName: 'monkey-98455$EXT', referralUrl: ''),
  CardSymbol(emoji: '🎬', fileName: 'movie-98481$EXT', referralUrl: ''),
  CardSymbol(emoji: '🧁', fileName: 'muffin-1775046$EXT', referralUrl: ''),
  CardSymbol(emoji: '🍄', fileName: 'mushroom-576463$EXT', referralUrl: ''),
  CardSymbol(emoji: '📰', fileName: 'news-97862$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔒', fileName: 'padlock-308589$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐧', fileName: 'penguin-42936$EXT', referralUrl: ''),
  CardSymbol(emoji: '📸', fileName: 'photos-98444$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐦', fileName: 'pigeon-42590$EXT', referralUrl: ''),
  CardSymbol(emoji: '➕', fileName: 'plus-24844$EXT', referralUrl: ''),
  CardSymbol(emoji: '🍿', fileName: 'popcorn-155602$EXT', referralUrl: ''),
  CardSymbol(emoji: '❓', fileName: 'question-mark-350168$EXT', referralUrl: ''),
  CardSymbol(emoji: '🌧️', fileName: 'rain-98538$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐀', fileName: 'rat-152162$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔄', fileName: 'reload-97640$EXT', referralUrl: ''),
  CardSymbol(emoji: '🇷🇺', fileName: 'russian-5587826$EXT', referralUrl: ''),
  CardSymbol(emoji: '🧂', fileName: 'salt-3092887$EXT', referralUrl: ''),
  CardSymbol(emoji: '🎅', fileName: 'santa-claus-153309$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '☠️', fileName: 'skull-and-crossbones-30325$EXT', referralUrl: ''),
  CardSymbol(emoji: '😊', fileName: 'smiley-1635449$EXT', referralUrl: ''),
  CardSymbol(emoji: '❄️', fileName: 'snowflake-6291986$EXT', referralUrl: ''),
  CardSymbol(emoji: '⛄', fileName: 'snowman-1106004$EXT', referralUrl: ''),
  CardSymbol(emoji: '🧦', fileName: 'sock-4594124$EXT', referralUrl: ''),
  CardSymbol(emoji: '🔊', fileName: 'speaker-98507$EXT', referralUrl: ''),
  CardSymbol(emoji: '⭐', fileName: 'star-1292832$EXT', referralUrl: ''),
  CardSymbol(emoji: '⭐', fileName: 'starfish-46584$EXT', referralUrl: ''),
  CardSymbol(emoji: '🛑', fileName: 'stop-32577$EXT', referralUrl: ''),
  CardSymbol(emoji: '🍓', fileName: 'strawberry-36949$EXT', referralUrl: ''),
  CardSymbol(emoji: '☀️', fileName: 'sun-29249$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🌡️', fileName: 'thermometer-5118701$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐅', fileName: 'tiger-160601$EXT', referralUrl: ''),
  CardSymbol(emoji: '🧰', fileName: 'toolbox-5652687$EXT', referralUrl: ''),
  CardSymbol(emoji: '🛠️', fileName: 'tools-98391$EXT', referralUrl: ''),
  CardSymbol(emoji: '🗑️', fileName: 'trash-can-28142$EXT', referralUrl: ''),
  CardSymbol(emoji: '🌳', fileName: 'tree-576847$EXT', referralUrl: ''),
  CardSymbol(emoji: '☔', fileName: 'umbrella-1032758$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🇺🇳', fileName: 'united-nations-311419$EXT', referralUrl: ''),
  CardSymbol(emoji: '💊', fileName: 'vitamins-26622$EXT', referralUrl: ''),
  CardSymbol(emoji: '⚠️', fileName: 'warning-838655$EXT', referralUrl: ''),
  CardSymbol(emoji: '⌚', fileName: 'watch-5905171$EXT', referralUrl: ''),
  CardSymbol(emoji: '🏆', fileName: 'win-5834110$EXT', referralUrl: ''),
  CardSymbol(emoji: '🧭', fileName: 'wind-rose-6294453$EXT', referralUrl: ''),
  CardSymbol(emoji: '🧼', fileName: 'wipe-97583$EXT', referralUrl: ''),
  CardSymbol(emoji: '🚗', fileName: 'car-42552$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐱', fileName: 'cat-6484941$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🍦', fileName: 'cone-ice-cream-5205265$EXT', referralUrl: ''),
  CardSymbol(
      emoji: '🐶', fileName: 'dog-portrait-6886638$EXT', referralUrl: ''),
  CardSymbol(emoji: '⚽', fileName: 'football-152827$EXT', referralUrl: ''),
  CardSymbol(emoji: '🐲', fileName: 'godzilla-5310877$EXT', referralUrl: ''),
  CardSymbol(emoji: '🌭', fileName: 'hot-dog-6847122$EXT', referralUrl: ''),
  CardSymbol(emoji: '🥤', fileName: 'juice-25189$EXT', referralUrl: ''),
  CardSymbol(emoji: '😎', fileName: 'stop-32577$EXT', referralUrl: ''),
  CardSymbol(emoji: '🚀', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🍕', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🧬', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🦨', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🦖', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🦒', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🦏', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🧵', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🦴', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🧲', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🧤', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🦉', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🪃', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🦄', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🇨🇦', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🇧🇷', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🇨🇵', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '💈', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🪬', fileName: '', referralUrl: ''),
  CardSymbol(emoji: '🇺🇸', fileName: '', referralUrl: ''),
];
